### PR TITLE
Correct some typos, update some demo link, rename duplicate variables, change value type, correct value

### PR DESCRIPTION
**Pull request by ilexwg**
- correct some typos
- update some demo link
- rename some duplicate variables
- change some string values to int (should give int type)
- correct imageVerticalAlign value

### CODE REVIEW

**Comment by davidjgraph** [comment]
What problem is this fixing?

**Comment by ilexwg** [comment]
> What problem is this fixing?

Which commit do you mean?

**Comment by davidjgraph** [comment]
The string to int changes are the main question. But if you are fixing different issues they need to be in different PRs. If some of the changes are correct and some not, we can only accept or reject the whole thing. Thanks.

**Comment by ilexwg** [comment]
> The string to int changes are the main question. But if you are fixing different issues they need to be in different PRs. If some of the changes are correct and some not, we can only accept or reject the whole thing. Thanks.

Ok! I got it! Thanks.
I will make different PRs.

**Pull request closed without merging**
