### PR TITLE
update the js-doc

### PR DESCRIPTION
**Pull request by breezefaith**
Repeated comments in the document have been modified。

### CODE REVIEW

**Comment by davidjgraph** [comment]
The comment changes are fine. However, the scope change is not correct, not we cannot merge this. We cannot merge part of a PR, so the entire thing has to be rejected, unfortunately.

**Comment by breezefaith** [comment]
> The comment changes are fine. However, the scope change is not correct, not we cannot merge this. We cannot merge part of a PR, so the entire thing has to be rejected, unfortunately.

Could you tell me what does "the scope change is not correct" means?

**Comment by davidjgraph** [comment]
https://github.com/jgraph/mxgraph2/pull/46/commits/f66c24876d8f09cfbeed009c356d16e3b8ffb8d8 you haven't explained the technical justification for the code change. The PR says it's a documentation change, but you have two different PRs in one.

**Comment by breezefaith** [comment]
Oh, I get it now

**Pull request closed without merging**
