### PR TITLE
Fix some documentation bugs and some minor bugs

### PR DESCRIPTION
**Pull request by Mingun**

### CODE REVIEW

**Comment by Mingun** [comment]
Some comments or objections?

**Comment by davidjgraph** [comment]
We just shut down mostly for summer, we'll be back in September. But, thanks for the submission.

**Comment by Mingun** [comment]
Glad to hear that not everything a lost and project is alive. Thanks

**Comment by davidjgraph** [comment]
Yup, we get there eventually. Thanks for the submission.

**Pull request merged**
